export const metadata = {
  title: 'ProMarketing | Contact Us',
  description: 'Generated by create next app',
}

export default function Contact() {
  return (
    <>
      <div className="bg-sky-50">
        <div className="mx-auto max-w-2xl px-4 py-10 sm:px-6 lg:px-8 lg:py-14 text-center font-serif">
          <h1 class="text-3xl font-semibold text-blue-700 sm:text-4xl">Contact us</h1>
          <p class="mt-1 text-lg text-gray-600">We&#39;d love to talk about how we can help you.</p>
          <form className="mt-5 bg-white text-left p-4 sm:p-6 lg:p-8 border rounded-lg shadow-lg shadow-gray-100">
            <h2 class="text-xl mb-2 font-semibold text-gray-800">Fill in the form</h2>
            <div className="sm:flex sm:space-x-4">
              <input
                className=" w-full my-3 p-3 text-lg rounded-lg border border-gray-400"
                type="text"
                name="name"
                placeholder="Name"
              />
              <input
                className="w-full my-3 p-3 text-lg rounded-lg border border-gray-400"
                type="tel"
                name="mobile"
                placeholder="Mobile No."
              />
            </div>
            <textarea
              className="w-full min-h-[140px] my-3 p-3 text-lg rounded-lg border border-gray-400"
              name="message"
              placeholder="Message"
            />
            <input
              className="w-full my-3 p-3 text-lg rounded-lg cursor-pointer bg-blue-700 text-white"
              type="submit"
              value="Send enquiry"
            />
            <p className="text-center text-md text-gray-600">We'll get back to you in 1-2 business days.</p>
          </form>
        </div>
      </div>
    </>
  )
}