export const metadata = {
  title: 'ProMarketing | About Us',
  description: 'Generated by create next app',
}

export default function About() {
  return (
    <>
      <main className="p-3 bg-sky-50 font-serif">
        <div className="text-center p-3">
          <h1 class="text-3xl font-semibold text-blue-700 sm:text-4xl">About Us</h1>
        </div>
        <div className="max-w-3xl m-auto bg-white md:my-3 p-3 space-y-3 md:space-y-5 text-justify border rounded-lg shadow-lg shadow-gray-100">
          <p className="text-lg text-gray-800">Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus nulla similique eum minima nemo incidunt iusto recusandae magnam molestiae consectetur maiores ducimus, earum assumenda officia corporis. Rerum sequi provident optio eveniet! Blanditiis exercitationem atque officia reprehenderit cum cupiditate ex facere saepe autem! Esse exercitationem dolorum cupiditate quia magni. Vel, facere.</p>
          <figure>
            <img class="w-full object-cover rounded-xl" src="https://images.unsplash.com/photo-1670272498380-eb330b61f3cd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80" alt="Image Description" />
            <figcaption class="mt-3 text-sm text-center text-gray-500">
              A man and a woman looking at a cell phone.
            </figcaption>
          </figure>
          <p className="text-lg text-gray-800">Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus nulla similique eum minima nemo incidunt iusto recusandae magnam molestiae consectetur maiores ducimus, earum assumenda officia corporis. Rerum sequi provident optio eveniet! Blanditiis exercitationem atque officia reprehenderit cum cupiditate ex facere saepe autem! Esse exercitationem dolorum cupiditate quia magni. Vel, facere.</p>
          <p className="text-lg text-gray-800">Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus nulla similique eum minima nemo incidunt iusto recusandae magnam molestiae consectetur maiores ducimus, earum assumenda officia corporis. Rerum sequi provident optio eveniet! Blanditiis exercitationem atque officia reprehenderit cum cupiditate ex facere saepe autem! Esse exercitationem dolorum cupiditate quia magni. Vel, facere.</p>
          <p className="text-lg text-gray-800">Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus nulla similique eum minima nemo incidunt iusto recusandae magnam molestiae consectetur maiores ducimus, earum assumenda officia corporis. Rerum sequi provident optio eveniet! Blanditiis exercitationem atque officia reprehenderit cum cupiditate ex facere saepe autem! Esse exercitationem dolorum cupiditate quia magni. Vel, facere.</p>
          <p className="text-lg text-gray-800">Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus nulla similique eum minima nemo incidunt iusto recusandae magnam molestiae consectetur maiores ducimus, earum assumenda officia corporis. Rerum sequi provident optio eveniet! Blanditiis exercitationem atque officia reprehenderit cum cupiditate ex facere saepe autem! Esse exercitationem dolorum cupiditate quia magni. Vel, facere.</p>
        </div>
      </main>
    </>
  )
}